rm simulation
rm sim.o
rm simulation.o
rm servicenode1alg.o
rm servicenode2alg.o
rm servicenode3alg.o
rm servicenode4alg.o
rm servicenode5alg.o
rm rngs.o
rm rvms.o
rm randomGeneratorFunctions.o
rm ./data/finite/servicenode1.dat
rm ./data/finite/servicenode2.dat
rm ./data/finite/servicenode3.dat
rm ./data/finite/servicenode4.dat
rm ./data/finite/servicenode5.dat
rm ./data/infinite/servicenode1.dat
rm ./data/infinite/servicenode2.dat
rm ./data/infinite/servicenode3.dat
rm ./data/infinite/servicenode4.dat
rm ./data/infinite/servicenode5.dat
